# Generated by Django 3.1.4 on 2020-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201202_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
